version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "com.googlecode.maven-download-plugin:download-maven-plugin"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "weekly"
    labels:
        - "dependencies"